# AUTO-GENERATED by workspace-scripts/sync-heartbeat-routing.mjs from src/config.ts.
# DO NOT EDIT BY HAND. Canonical source: src/config.ts
# (ALERT_TOPIC / COACH_TOPIC / WARDROBE_TOPIC / CHAT_ID).
# Regenerate: npm run sync-routing  (also runs as postbuild after `npx tsc`).
# Shell single-source for Telegram topic routing used by cron/heartbeat scripts.
CLAW_CHAT_ID=""
CLAW_ALERTS_TOPIC="1000005"
CLAW_COACH_TOPIC="1000003"
CLAW_WARDROBE_TOPIC="1000001"
